microsoft/FluidExamples

brainstorm/src/index.tsx
changed tinylicious port to 7070
=> fix port number

build.yml, cra-demo/package.json, fluid-react-starter/package.json
Adds both examples to the PR build pipeline:
=> Add react starter and cra to build

brainstorm/package-lock.json, build.yml, lerna.json, multi-framework-diceroller/.gitignore, multi-framework-diceroller/README.md, multi-framework-diceroller/package-lock.json, multi-framework-diceroller/package.json, multi-framework-diceroller/src/app.js, multi-framework-diceroller/src/index.html, multi-framework-diceroller/src/view/index.js, multi-framework-diceroller/src/view/jsView.js, multi-framework-diceroller/src/view/reactView.jsx, multi-framework-diceroller/src/view/vueView.js, multi-framework-diceroller/src/view/wcView.js, multi-framework-diceroller/webpack.config.js
The intention is to bring this demo over separate from hello world. Here we can show how the same data can be rendered in different view frameworks, and aren't limited to keeping the demo incredibly sparse. Still a bit of a WIP, but wanted to port this over since i'll be removing the other views from the hello world repo.
=> add dice roller package

collaborative-text-area/src/App.tsx
Small code cleanup in Fluid Examples by removing else statement by returning early, using hooks instead of classical components, and object destructuring container
=> small code cleanup

audience-demo/src/App.js, audience-demo/src/UserIdSelection.js
Fixed naming for SelectUser component and style props.
=> Fix audience example

audience-demo/README.md, audience-demo/src/App.js, audience-demo/src/AudienceDisplay.js, audience-demo/src/UserIdSelection.js
autofill for container id from location.hash
=> Audience example fix

node-demo/package-lock.json, node-demo/package.json, node-demo/test/index.test.js, node-demo/test/nodeDemo.js
This PR adds test cases in node-demo example. spy call is used on console statement to capture the values and container id.
=> Testing in node-demo 

multi-framework-diceroller/package-lock.json, multi-framework-diceroller/package.json, node-demo/package-lock.json, node-demo/package.json
update fluidframework packages to internal 2.0 for node demo and dice roller demo
=> Node demo and dice roller demo update to tinylicious 2.0 itnernal

build.yml
Add a schedule to automatically run builds on a daily basis
[AB#4694](https://dev.azure.com/fluidframework/internal/_workitems/edit/4694)
=> Add schedule to build apps daily

angular-demo/README.md, audience-demo/README.md, collaborative-text-area/README.md, multi-framework-diceroller/README.md, node-demo/README.md, react-demo/README.md, react-starter-template/README.md
Update app running instructions to be more consistent and explicit.
=> docs: Clarify app usage instructions

.gitignore, angular-demo/jest.config.js, angular-demo/package-lock.json, angular-demo/package.json, audience-demo/jest.config.js, audience-demo/package-lock.json, audience-demo/package.json, brainstorm/jest.config.js, brainstorm/package-lock.json, brainstorm/package.json, build.yml, collaborative-text-area/jest.config.js, collaborative-text-area/package-lock.json, collaborative-text-area/package.json, multi-framework-diceroller/jest.config.js, multi-framework-diceroller/package-lock.json, multi-framework-diceroller/package.json, node-demo/.mocharc.cjs, node-demo/package-lock.json, node-demo/package.json, react-demo/jest.config.js, react-demo/package-lock.json, react-demo/package.json, react-starter-template/jest.config.js, react-starter-template/package-lock.json, react-starter-template/package.json
CI was set up to publish generated test reports, but none were being generated. This PR updates our testing logic to ensure test reports are correctly generated by test runs.
E.g.
=> tools: Update test infra to generate test reports locally and in CI

build.yml, react-starter-template/test/App.test.tsx
This PR increases the timeout for react-starter-template tests, since they were consistently timing out in automated test pipelines.
=> Increase timeout for react-starter-template tests

angular-demo/jest-puppeteer.config.js, angular-demo/test/App.test.ts, angular-demo/tsconfig.json, audience-demo/jest-puppeteer.config.js, brainstorm/jest-puppeteer.config.js, build.yml, collaborative-text-area/jest-puppeteer.config.js, multi-framework-diceroller/jest-puppeteer.config.js, react-demo/jest-puppeteer.config.js, react-starter-template/jest-puppeteer.config.js
Add v2.0_internal to yml file and fix failing test
=> Add v2.0_internal to yml file

angular-demo/package-lock.json, angular-demo/package.json, audience-demo/package-lock.json, audience-demo/package.json, brainstorm/package-lock.json, brainstorm/package.json, collaborative-text-area/package-lock.json, collaborative-text-area/package.json, multi-framework-diceroller/package-lock.json, multi-framework-diceroller/package.json, node-demo/package-lock.json, node-demo/package.json, react-demo/package-lock.json, react-demo/package.json, react-starter-template/package-lock.json, react-starter-template/package.json
Bump internal branch 2.0 packages to 2.0.0-internal.7.2.0
=> Bump internal branch to 2.0.0-internal.7.2.0

angular-demo/package-lock.json, angular-demo/package.json, audience-demo/package-lock.json, audience-demo/package.json, brainstorm/package-lock.json, brainstorm/package.json, collaborative-text-area/package-lock.json, collaborative-text-area/package.json, multi-framework-diceroller/package-lock.json, multi-framework-diceroller/package.json, node-demo/package-lock.json, node-demo/package.json, react-demo/package-lock.json, react-demo/package.json, react-starter-template/package-lock.json, react-starter-template/package.json
bumped fluidframework internal packages from 2.0.0-internal.7.2.0 to 2.0.0-internal.7.2.2.
=> bump package dependencies to 2.0.0-internal.7.2.2

angular-demo/package-lock.json, angular-demo/package.json, audience-demo/package-lock.json, audience-demo/package.json, brainstorm/package-lock.json, brainstorm/package.json, collaborative-text-area/package-lock.json, collaborative-text-area/package.json, multi-framework-diceroller/package-lock.json, multi-framework-diceroller/package.json, node-demo/package-lock.json, node-demo/package.json, react-demo/package-lock.json, react-demo/package.json, react-starter-template/package-lock.json, react-starter-template/package.json
This PR bumps all FF dependencies to `^2.0.0-internal.7.3.0`
=> bump FF package dependencies to 2.0.0-internal.7.3.0

angular-demo/package-lock.json, angular-demo/package.json, audience-demo/package-lock.json, audience-demo/package.json, brainstorm/package-lock.json, brainstorm/package.json, collaborative-text-area/package-lock.json, collaborative-text-area/package.json, multi-framework-diceroller/package-lock.json, multi-framework-diceroller/package.json, node-demo/package-lock.json, node-demo/package.json, react-demo/package-lock.json, react-demo/package.json, react-starter-template/package-lock.json, react-starter-template/package.json
Manually tested each example and verified still working as expected.
=> Update dependencies to v8 internal

angular-demo/jest.config.js, react-demo/jest.config.js
increase timeout for angular and react demo, both tests failed on different runs due to timeout with no code changes.
=> increase timeout for angular and react demo

brainstorm/package-lock.json, item-counter-spe/package-lock.json, item-counter/package-lock.json, package-lock.json
Updated via `npm update` and `npm audit fix`
=> build: Update dependencies

brainstorm/package-lock.json, brainstorm/package.json, brainstorm/src/output.css, item-counter-spe/package-lock.json, item-counter-spe/package.json, item-counter-spe/src/output.css, item-counter/package-lock.json, item-counter/package.json
Updates `prettier` from `^2.7.1` to `^3.3.3`.
=> build: Update dependencies on `prettier` and update code formatting

brainstorm/package-lock.json, brainstorm/package.json, item-counter/package-lock.json, item-counter/package.json
Resolving dependabot alerts that it got stuck on.
=> Update webpack to 5.94.0

.github/dependabot.yml, package.json
Also update issues link.  Basically an updated version of #545
=> Enable dependabot for item-counter-spe

brainstorm/package-lock.json, item-counter-spe/package-lock.json
Basically same as #1069 but for the other two examples.  Dependabot seems stuck on creating the updates for those two :-/
=> Update versions of Express and body-parser

brainstorm/package-lock.json, item-counter/package-lock.json
Dependabot got stuck on these two.  Similar to #1105 .
=> Update express and send dependencies

brainstorm/README.md, brainstorm/src/app_load.tsx, brainstorm/src/infra/azure/azureClientProps.ts, brainstorm/src/infra/fluid.ts, brainstorm/src/infra/spe/speClientProps.ts, brainstorm/src/start/azure_start.ts, brainstorm/src/start/spe_start.ts
Adds Fluid Framework Devtools initialization to the Brainstorm app
=> feat: Add Fluid Devtools to the Brainstorm app

brainstorm/README.md, brainstorm/package-lock.json, brainstorm/package.json
Mostly the same as https://github.com/microsoft/FluidExamples/pull/1161 but for brainstorm
=> Cleanup brainstorm

item-counter-spe/.env.defaults
See title. Missed during a previous PR that added the setting.
=> Add SPE_ENTRA_TENANT_ID to .env.defaults

item-counter-spe/package-lock.json
=> Update express and cookie versions for spe example

.github/dependabot.yml
=> feat(dependabot): Add Dual dependabot configs to update fluid packages daily while others weekly

brainstorm/package-lock.json, brainstorm/package.json, item-counter-spe/package-lock.json, item-counter-spe/package.json, item-counter/package-lock.json, item-counter/package.json
Updated in all 3 packages to `15.13.0`.
=> build(deps): Update `globals`

brainstorm/package-lock.json, brainstorm/package.json, item-counter-spe/package-lock.json, item-counter-spe/package.json, item-counter/package-lock.json, item-counter/package.json, package-lock.json, package.json
Dependabot PRs are still not running required checks. Looking into this but still unsure, maybe repo admin can look into [branch protection rules](https://github.com/orgs/community/discussions/26698#discussioncomment-3252954). Anyways, manually bumping packages here.
=> build(deps): Update dependencies

brainstorm/package-lock.json, brainstorm/package.json
The CI build does not seem to trigger for three of the dependabot PRs. Hence I have opened a manual PR to update the packages.
1. https://github.com/microsoft/FluidExamples/pull/1423
2. https://github.com/microsoft/FluidExamples/pull/1422
3. https://github.com/microsoft/FluidExamples/pull/1419
=> build(deps-dev): Bump webpack, @azure/identity and playwright

brainstorm/src/schema/app_schema.ts
Fixed a typo, adjusted a confusing comment, and moved some when lastChanged is set to be consistent with other functions,
=> Minor schema improvements in brainstorm
