microsoft/FluidExamples

.github/ISSUE_TEMPLATE/config.yml

We want our issues to go to the FluidFramework repo where we can manage all our issues.

add issue template

---

multi-framework-diceroller/README.md
multi-framework-diceroller/src/app.js
multi-framework-diceroller/src/view/jsView.js
multi-framework-diceroller/src/view/reactView.jsx
multi-framework-diceroller/src/view/vueView.js
multi-framework-diceroller/src/view/wcView.js

Added readme and comment instructions about loading other views. Also changed function names to be a little more clear. 
I removed the 'render' from `renderDiceRoller` because `jsDiceRoller as diceRoller` seemed easier to understand than `jsDiceRoller as renderDiceRoller`, and I didn't want to go with `jsRenderDiceRoller as renderDiceRoller` either.

Add instructions to multi view dice roller

---

multi-framework-diceroller/src/view/reactView.jsx
multi-framework-diceroller/src/view/vueView.js
multi-framework-diceroller/src/view/wcView.js

I'm going to point directly to the view files in the docs, so I want to make sure that each view is able to define how to render that view.

add instructions in view files for rendering that view

---

multi-framework-diceroller/package-lock.json
multi-framework-diceroller/package.json

This example doesn't use `AzureClient` so we can remove the package from its dependencies

Remove azureclient dep from mfwd

---

react-demo/README.md

A user reached out to point out the outdated README for react-demo. This PR aims to address the [issue](https://github.com/microsoft/FluidFramework/issues/7726) the user created. 
We were not able to replicate the 2nd issue the user pointed out, so the implementation will remained as `location.hash` instead of `window.location.hash`.

fixed outdated react-demo README

---

node-demo/package.json
node-demo/src/index.js

`readline-async` seems to be causing `Ctrl-C` not to work once the application is running, so replacing it with a simpler option that keeps it working.
Partially fixes https://github.com/microsoft/FluidFramework/issues/9208 (pending a PR to fix the [corresponding code in the documentation](https://github.com/microsoft/FluidFramework/blob/main/docs/content/docs/recipes/node.md)).

Replace readline-async with readline-sync

---

README.md
angular-demo/README.md
audience-demo/README.md
brainstorm/README.md
brainstorm/package-lock.json
brainstorm/src/view/BrainstormView.tsx
build.yml
collaborative-text-area/package-lock.json
collaborative-text-area/package.json
multi-framework-diceroller/README.md
multi-framework-diceroller/jest-puppeteer.config.js
multi-framework-diceroller/package-lock.json
multi-framework-diceroller/package.json
node-demo/README.md
node-demo/package-lock.json
node-demo/package.json
package-lock.json
react-demo/README.md
react-demo/package.json
react-starter-template/README.md
react-starter-template/package-lock.json

This PR includes misc. cleanup done while verifying all of the apps are working as intended. They include:
* package-lock updates
* Misc. documentation improvements (mostly formatting)
* Updating package app start flows to ensure all packages use the same flow (`npx tinylicious` in one terminal, `npm install` and `npm start` in another).
* Fix a potential bug in `BrainstormView` where React state was not correctly updated when dependency (container) changed. Fix is to use `useMemo` in place of `useState`.

build: Misc. cleanup

---

audience-demo/jest.config.js
collaborative-text-area/jest.config.js

Tests seems to be non-deterministically timing out often enough that most CI runs fail.
This is an attempt to get CI to pass with no unrelated changes.

Increase Timeouts

---

angular-demo/package-lock.json
angular-demo/package.json
brainstorm/package-lock.json
brainstorm/package.json
collaborative-text-area/package-lock.json
collaborative-text-area/package.json
multi-framework-diceroller/package-lock.json
multi-framework-diceroller/package.json
node-demo/package.json
package-lock.json
package.json
react-demo/package-lock.json
react-demo/package.json
react-starter-template/package-lock.json
react-starter-template/package.json

Require at least Node 18.
This removes support for older unsupported major versions of NodeJs.

Only support Node 18 and newer

---

angular-demo/package-lock.json
angular-demo/package.json
audience-demo/package-lock.json
audience-demo/package.json
audience-demo/src/AudienceDisplay.js
brainstorm/README.md
brainstorm/package-lock.json
brainstorm/package.json
brainstorm/src/Config.ts
collaborative-text-area/package-lock.json
collaborative-text-area/package.json
multi-framework-diceroller/package-lock.json
multi-framework-diceroller/package.json
node-demo/package-lock.json
node-demo/package.json
react-demo/package-lock.json
react-demo/package.json
react-starter-template/package-lock.json
react-starter-template/package.json

Also switches to test-runtime-utils in place of test-client-utils (which was discontinued a while back) and bumps build-common to 2.0.2.

Bump to internal 7.1.0

---

angular-demo/README.md
angular-demo/package-lock.json
angular-demo/package.json
audience-demo/README.md
audience-demo/package-lock.json
audience-demo/package.json
brainstorm/README.md
brainstorm/package-lock.json
brainstorm/package.json
collaborative-text-area/README.md
collaborative-text-area/package-lock.json
collaborative-text-area/package.json
multi-framework-diceroller/README.md
multi-framework-diceroller/package-lock.json
multi-framework-diceroller/package.json
node-demo/README.md
node-demo/package-lock.json
node-demo/package.json
react-demo/README.md
react-demo/package-lock.json
react-demo/package.json
react-starter-template/README.md
react-starter-template/package-lock.json
react-starter-template/package.json

Standardizes all examples to use `@fluidframework/azure-local-service` instead of tinylicious

Standardize examples to use @fluidframework/azure-local-service instead of tinylicious

---

brainstorm/README.md
item-counter/README.md

aka.ms/fluid was not going to the website, it was going to a file in the repo, fixed it to go to the actual website

Tiny bug was causing fluid site to 404 in readme for brainstorm and item-counter

---

brainstorm/package-lock.json
brainstorm/package.json

This avoids npx asking if its ok to install when running `npm run start:server` , and pins exact versions of the transitive deps in the package lock.

Add azure-local-service dep

---

brainstorm/src/index.tsx
brainstorm/src/react/buttonux.tsx
brainstorm/src/react/canvasux.tsx
brainstorm/src/react/groupux.tsx
brainstorm/src/react/noteux.tsx
brainstorm/src/react/ux.tsx
brainstorm/src/schema/app_schema.ts
brainstorm/src/utils/app_helpers.ts

Demo recursive schema support in Brainstorm. As far as I know this is the first non-trivial use of the new recursive schema APIs, so this was a valuable test of those, as well as a demo for them.
Additionally, more functions were moved onto the schema as methods, root and group handling were unified (via Items), some comments were converted to doc comments to help with IntelliSense and show off that doc comments on fields in schema actually work.
A few places stopped taking in parents explicitly and instead look them up in the tree.
Tree.is has been used instead of instancof since it works in more cases (for example with leaf nodes and POJO mode schema): this is more of just encouraging a more general pattern than a fix since instancof works fine where it was used.

Allow recursion in brainstorm example

---

brainstorm/src/react/canvasux.tsx

This PR fixes a bug in the brainstorm app where the users count does not properly update on startup. This is because we setup the event listener, but it does not fire until another `"membersChanged"` event. To fix this, we can call `updateMembers()` to ensure it gets the latest audience data on startup.

Fix users count in brainstorm app on startup

---

brainstorm/package-lock.json
brainstorm/package.json
item-counter-spe/package-lock.json
item-counter-spe/package.json
item-counter/package-lock.json
item-counter/package.json

Updates `webpack-dev-server`, resolving console errors reported when webpack-bundling our apps.
```shell
(node:295029) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
Also updates `webpack-dev-server` for good measure.

build: Update `html-webpack-plugin` and `webpack-dev-server`

---

brainstorm/package-lock.json
brainstorm/package.json
item-counter-spe/package-lock.json
item-counter-spe/package.json
item-counter/package-lock.json
item-counter/package.json
package-lock.json
package.json

Discovered via `npm outdated`. See package.json changes for the complete list of updates.
Also removes an unused dependency on `@headlessui/react`.

build: Update outdated dependencies

---

.github/dependabot.yml

Based on my read of https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
It seems atypical to repeat package-ecosystem for the same ecosystem (this is meant more for when multiple package-ecosystems are in play).  Merge these all together, and instead use `directories` to specify all directories with a package.json file.
Our allow rule only permits updating FF dependencies, but AFAICT there's no reason we wouldn't want updates to other dependencies too.  Drop allow field to allow all dependencies to be updated.
FF packages are best updated all in sync, rather than opening multiple PRs for each package individually (as recently happened with #1034 through #1043).  Use the groups field to encourage grouping these …

Update dependabot to allow updating all dependencies and group FF dependencies

---

brainstorm/package-lock.json
brainstorm/package.json
item-counter-spe/package-lock.json
item-counter-spe/package.json
item-counter/package-lock.json
item-counter/package.json

Looking at the dependabot bumps for `dotenv-webpack`, I realized we also had an unused dependency on `dotenv` (presumably from a prior implementation that used it instead).  Removing the unused dependency.

Remove unused dotenv dependency

---

item-counter-spe/README.md
item-counter-spe/src/index.tsx
item-counter-spe/src/infra/authHelper.ts

I believe this change still allows the app to live in the "common" Entra tenant owned by Microsoft, but now would require the user to pass its id explicitly.
I had to make this change to make the app work with an M365/Entra tenant from my developer account.

Make sample SPE app work for single-tenant Entra Apps

---

.github/dependabot.yml

To reduce noise, this PR reduces dependabot updates to weekly and groups all eslint-related updates into a single PR.

Drop dependabot frequency to weekly and group eslint updates

---

item-counter/README.md
item-counter/package-lock.json
item-counter/package.json

Use dev dependencies instead of npx so versions are controlled by package lock.
Ran npm audit to resolve three security vulnerabilities.
Add note to readme about dev server output.

Avoid needless npx, do an npm audit fix, improve readme

---

brainstorm/src/schema/app_schema.ts

Apply workaround noted in https://github.com/microsoft/FluidFramework/pull/22763/files#diff-4e56bb12cb4dab4f811a1f027a4cbb587a1c8d183ceeb15847059abd93323ae1R82 which will be needed to updated to fluid 2.4 when released.
Which this fix, brainstorm is confirmed to retain its existing 39 compile errors and 0 build errors when updating to a recent release candidate.

Use objectRecursive for Group

---

.github/dependabot.yml

These should all be updated in sync anyway, and with a group dependabot will also bundle the PRs for all examples into a single PR too.

Make a dependabot group for React

---

brainstorm/src/react/noteux.tsx

Repro: 
- Start brainstorm app
- Add 2 clients
- Create a note and like it
- See that remote like is updated but local state is not 
- Local state only updates after another change to node 
- Continue liking and unliking 
- state inconsistencies 
Fix: changes to votes array are not considered as changes to Notes Tree Node. We instead need to treat the array as it's own Tree node.

fix(brainstorm): local state for likes is inconsistent with remote state

---

.github/CODEOWNERS
.github/dependabot.yml

The reviewers option has been removed from dependabot’s configuration, as noted in this post: https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/. 
I wasn’t able to configure reviewers specifically for dependabot PRs. Instead, I added a CODEOWNERS file that assigns @microsoft/fluid-cr-devx as reviewers for any PR that modifies package.json or package-lock.json.

Add CODEOWNERS file
